spring:
  profiles:
    active: "dev"
    group:
      dev:
        - "common"
        - "dev"
      test:
        - "common"
        - "test"
#---
#spring:
#  profiles:
#    include:
#      - "common"
#      - "dev"
#---
#spring:
#  profiles:
#    include:
#      - "common"
#      - "test"
#---